version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: smart_supply_chain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smart_supply_chain
      - DATABASE_URL_ASYNC=postgresql+asyncpg://postgres:postgres@db:5432/smart_supply_chain
      - SECRET_KEY=your-secret-key-here-make-it-long-and-random
      - DEBUG=True
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=["http://localhost:3000", "http://localhost:5173"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: 