"""add_purchase_order_tables

Revision ID: 814b8609dab0
Revises: a5636eb17571
Create Date: 2025-06-29 00:57:52.987514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814b8609dab0'
down_revision = 'a5636eb17571'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 